<a href="https://colab.research.google.com/github/Capaquira/projectsLivreLow-code/blob/Notebooks/EnhancedML_skidlearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
!wget -q https://storage.googleapis.com/low-code-ai-book/car_prices_train.csv
!wget -q https://storage.googleapis.com/low-code-ai-book/car_prices_valid.csv
!wget -q https://storage.googleapis.com/low-code-ai-book/car_prices_test.csv

In [21]:
import pandas as pd

train_df = pd.read_csv('./car_prices_train.csv')
valid_df = pd.read_csv('./car_prices_valid.csv')
test_df = pd.read_csv('./car_prices_test.csv')

In [22]:
train_df.head()

,Unnamed: 0,year,make,model,trim,body,transmission,state,condition,odometer,color,interior,mmr,sellingprice
0,0,2012,Infiniti,G Sedan,G37 Journey,g sedan,automatic,fl,4.2,32580.0,blue,beige,18500,17600
1,1,2012,Chevrolet,Cruze,LS,Sedan,automatic,pa,2.8,17718.0,blue,black,9725,10400
2,2,2005,Jeep,Wrangler,X,SUV,manual,pa,2.1,74107.0,blue,black,12100,10100
3,3,2011,Kia,Sorento,SX,SUV,automatic,tn,4.0,99042.0,black,black,12000,13500
4,4,2002,Volkswagen,New Beetle,GLS,Hatchback,automatic,ca,1.9,197117.0,green,black,1225,800

In [23]:
train_df.describe(include='all')

,Unnamed: 0,year,make,model,trim,body,transmission,state,condition,odometer,color,interior,mmr,sellingprice
count,385000.000000,385000.000000,385000,385000,385000,385000,385000,385000,385000.000000,385000.000000,385000,385000,385000.000000,385000.000000
unique,NaN,NaN,53,765,1489,85,2,34,NaN,NaN,20,17,NaN,NaN
top,NaN,NaN,Ford,Altima,Base,Sedan,automatic,fl,NaN,NaN,black,black,NaN,NaN
freq,NaN,NaN,65690,13186,39949,142327,371576,61405,NaN,NaN,75692,169051,NaN,NaN
mean,192499.500000,2010.129517,NaN,NaN,NaN,NaN,NaN,NaN,3.341712,67621.340488,NaN,NaN,13709.615974,13559.620265
std,111140.071156,3.873780,NaN,NaN,NaN,NaN,NaN,NaN,1.116213,52443.329580,NaN,NaN,9513.524948,9589.154870
min,0.000000,1990.000000,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.000000,NaN,NaN,25.000000,1.000000
25%,96249.750000,2008.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.700000,28411.000000,NaN,NaN,7225.000000,7000.000000
50%,192499.500000,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,52010.000000,NaN,NaN,12200.000000,12100.000000
75%,288749.250000,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,98119.000000,NaN,NaN,18200.000000,18000.000000
max,384999.000000,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,999999.000000,NaN,NaN,182000.000000,183000.000000

In [24]:
valid_df.describe(include='all')

,Unnamed: 0,year,make,model,trim,body,transmission,state,condition,odometer,color,interior,mmr,sellingprice
count,48500.000000,48500.000000,48500,48500,48500,48500,48500,48500,48500.000000,48500.000000,48500,48500,48500.000000,48500.000000
unique,NaN,NaN,50,674,1099,73,2,34,NaN,NaN,20,17,NaN,NaN
top,NaN,NaN,Ford,Altima,Base,Sedan,automatic,fl,NaN,NaN,black,black,NaN,NaN
freq,NaN,NaN,8267,1647,5240,18158,46804,7684,NaN,NaN,9667,21009,NaN,NaN
mean,409249.500000,2010.101113,NaN,NaN,NaN,NaN,NaN,NaN,3.328346,67872.571567,NaN,NaN,13694.919072,13527.331402
std,14000.888365,3.896097,NaN,NaN,NaN,NaN,NaN,NaN,1.117352,52646.738174,NaN,NaN,9644.176866,9738.406087
min,385000.000000,1990.000000,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.000000,NaN,NaN,25.000000,100.000000
25%,397124.750000,2008.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.600000,28453.750000,NaN,NaN,7100.000000,6900.000000
50%,409249.500000,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.500000,52183.000000,NaN,NaN,12200.000000,12000.000000
75%,421374.250000,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,98563.750000,NaN,NaN,18150.000000,18000.000000
max,433499.000000,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,999999.000000,NaN,NaN,172000.000000,230000.000000

In [25]:
test_df.describe(include='all')

,Unnamed: 0,year,make,model,trim,body,transmission,state,condition,odometer,color,interior,mmr,sellingprice
count,48203.00000,48203.000000,48203,48203,48203,48203,48203,48203,48203.000000,48203.000000,48203,48203,48203.000000,48203.000000
unique,NaN,NaN,49,667,1104,71,2,34,NaN,NaN,20,17,NaN,NaN
top,NaN,NaN,Ford,Altima,Base,Sedan,automatic,fl,NaN,NaN,black,black,NaN,NaN
freq,NaN,NaN,8318,1660,5002,17845,46493,7522,NaN,NaN,9548,21174,NaN,NaN
mean,457601.00000,2010.095513,NaN,NaN,NaN,NaN,NaN,NaN,3.343031,68124.154887,NaN,NaN,13660.497272,13508.415991
std,13915.15185,3.897940,NaN,NaN,NaN,NaN,NaN,NaN,1.118882,52912.308000,NaN,NaN,9600.881718,9679.735513
min,433500.00000,1990.000000,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.000000,NaN,NaN,25.000000,100.000000
25%,445550.50000,2008.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.700000,28630.000000,NaN,NaN,7150.000000,6900.000000
50%,457601.00000,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,52395.000000,NaN,NaN,12200.000000,12000.000000
75%,469651.50000,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,98611.500000,NaN,NaN,18050.000000,18000.000000
max,481702.00000,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,999999.000000,NaN,NaN,170000.000000,173000.000000

In [26]:
from sklearn.preprocessing import FunctionTransformer, OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

y_train = train_df['sellingprice']
X_train = train_df.drop('sellingprice', axis=1)

def drop_columns(df, columns):
    return df.drop(columns, axis=1)

preproc_cols = FunctionTransformer(drop_columns, kw_args={"columns":['Unnamed: 0', 'mmr']})

numeric_columns = ['year', 'condition', 'odometer']
categorical_columns = ['make', 'model', 'trim', 'body',
                       'transmission', 'state', 'color', 'interior']

col_transformer = ColumnTransformer(
  [('ohe', OneHotEncoder(drop='if_binary', handle_unknown='infrequent_if_exist'),
      categorical_columns),
   ('minmax', MinMaxScaler(), numeric_columns)])

model = LinearRegression()

pipeline = Pipeline(steps=[('preproc_cols' , preproc_cols),
                           ('col_transformer', col_transformer),
                           ('model', model)])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('preproc_cols',
                 FunctionTransformer(func=<function drop_columns at 0x7c2c65c0a2a0>,
                                     kw_args={'columns': ['Unnamed: 0',
                                                          'mmr']})),
                ('col_transformer',
                 ColumnTransformer(transformers=[('ohe',
                                                  OneHotEncoder(drop='if_binary',
                                                                handle_unknown='infrequent_if_exist'),
                                                  ['make', 'model', 'trim',
                                                   'body', 'transmission',
                                                   'state', 'color',
                                                   'interior']),
                                                 ('minmax', MinMaxScaler(),
                                                  ['year', 'condition',
                                                   'odometer'])])),
                ('model', LinearRegression())])

In [27]:
import math
from sklearn.metrics import mean_squared_error, mean_absolute_error

y_valid = valid_df['sellingprice']
X_valid = valid_df.drop('sellingprice', axis=1)

print('R2:', pipeline.score(X_valid, y_valid))
print('RMSE:',math.sqrt(mean_squared_error(y_valid, pipeline.predict(X_valid))))
print('MAE:', mean_absolute_error(y_valid, pipeline.predict(X_valid)))

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

R2: 0.8808616613019848
RMSE: 3361.314686698366
MAE: 2051.09934705034

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [28]:
train_df.describe(include='all')

,Unnamed: 0,year,make,model,trim,body,transmission,state,condition,odometer,color,interior,mmr,sellingprice
count,385000.000000,385000.000000,385000,385000,385000,385000,385000,385000,385000.000000,385000.000000,385000,385000,385000.000000,385000.000000
unique,NaN,NaN,53,765,1489,85,2,34,NaN,NaN,20,17,NaN,NaN
top,NaN,NaN,Ford,Altima,Base,Sedan,automatic,fl,NaN,NaN,black,black,NaN,NaN
freq,NaN,NaN,65690,13186,39949,142327,371576,61405,NaN,NaN,75692,169051,NaN,NaN
mean,192499.500000,2010.129517,NaN,NaN,NaN,NaN,NaN,NaN,3.341712,67621.340488,NaN,NaN,13709.615974,13559.620265
std,111140.071156,3.873780,NaN,NaN,NaN,NaN,NaN,NaN,1.116213,52443.329580,NaN,NaN,9513.524948,9589.154870
min,0.000000,1990.000000,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.000000,NaN,NaN,25.000000,1.000000
25%,96249.750000,2008.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.700000,28411.000000,NaN,NaN,7225.000000,7000.000000
50%,192499.500000,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,52010.000000,NaN,NaN,12200.000000,12100.000000
75%,288749.250000,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,98119.000000,NaN,NaN,18200.000000,18000.000000
max,384999.000000,2015.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,999999.000000,NaN,NaN,182000.000000,183000.000000

In [29]:
train_df.describe().round(0)

       Unnamed: 0      year  condition  odometer       mmr  sellingprice
count    385000.0  385000.0   385000.0  385000.0  385000.0      385000.0
mean     192500.0    2010.0        3.0   67621.0   13710.0       13560.0
std      111140.0       4.0        1.0   52443.0    9514.0        9589.0
min           0.0    1990.0       -1.0       1.0      25.0           1.0
25%       96250.0    2008.0        3.0   28411.0    7225.0        7000.0
50%      192500.0    2012.0        4.0   52010.0   12200.0       12100.0
75%      288749.0    2013.0        4.0   98119.0   18200.0       18000.0
max      384999.0    2015.0        5.0  999999.0  182000.0      183000.0

# **Compartimientos de datos**

In [30]:
import pandas as pd

from sklearn.preprocessing import (OneHotEncoder, MinMaxScaler,
                                   FunctionTransformer,
                                   KBinsDiscretizer)
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

y_train = train_df['sellingprice']
X_train = train_df.drop('sellingprice', axis=1)

def preproc_cols(df, drop_cols):
    return df.drop(drop_cols, axis=1)

drop_cols = FunctionTransformer(preproc_cols, kw_args={"drop_cols":['Unnamed: 0', 'mmr']})
ohe = OneHotEncoder(drop='if_binary', handle_unknown='infrequent_if_exist', min_frequency=1)
minmax = MinMaxScaler()
bucket_cond = KBinsDiscretizer(n_bins=10, encode='onehot', strategy='uniform')

numeric_columns = ['year', 'odometer']
categorical_columns = ['make', 'model', 'trim', 'body',
                       'transmission', 'state', 'color', 'interior']

col_transformer = ColumnTransformer(
  [('ohe', ohe, categorical_columns),
   ('minmax', minmax, numeric_columns),
   ('bucket_cond', bucket_cond, ['condition'])])

pipeline = Pipeline(steps=[('drop_cols' , drop_cols),
                           ('col_transformer', col_transformer),
                           ('model', model)])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('drop_cols',
                 FunctionTransformer(func=<function preproc_cols at 0x7c2c65c0b100>,
                                     kw_args={'drop_cols': ['Unnamed: 0',
                                                            'mmr']})),
                ('col_transformer',
                 ColumnTransformer(transformers=[('ohe',
                                                  OneHotEncoder(drop='if_binary',
                                                                handle_unknown='infrequent_if_exist',
                                                                min_frequency=1),
                                                  ['make', 'model', 'trim',
                                                   'body', 'transmission',
                                                   'state', 'color',
                                                   'interior']),
                                                 ('minmax', MinMaxScaler(),
                                                  ['year', 'odometer']),
                                                 ('bucket_cond',
                                                  KBinsDiscretizer(n_bins=10,
                                                                   strategy='uniform'),
                                                  ['condition'])])),
                ('model', LinearRegression())])

In [31]:
print('R2:', pipeline.score(X_valid, y_valid))
print('RMSE:',math.sqrt(mean_squared_error(y_valid, pipeline.predict(X_valid))))
print('MAE:', mean_absolute_error(y_valid, pipeline.predict(X_valid)))

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

R2: 0.8842040261986036
RMSE: 3313.829294429968
MAE: 2033.1097243844124

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [32]:
(train_df.trim.value_counts() == 1).sum()

np.int64(124)

In [33]:
(valid_df.trim.value_counts() == 1).sum()

np.int64(273)

# **Cruzamiento de Caracteristicas**

In [36]:

import pandas as pd

from sklearn.preprocessing import (OneHotEncoder, MinMaxScaler,
                                   FunctionTransformer,
                                   KBinsDiscretizer)
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

y_train = train_df['sellingprice']
X_train = train_df.drop('sellingprice', axis=1)

def preproc_cols(df, drop_cols):

    df['model_trim'] = df['model'] + df['trim']
    df['model_trim'] = df['model_trim'].str.lower()

    df['color_interior'] = df['color'] + df['interior']
    df['color_interior'] = df['color_interior'].str.lower()

    return df.drop(drop_cols, axis=1)

drop_cols = FunctionTransformer(preproc_cols, kw_args={"drop_cols":['Unnamed: 0', 'mmr']})
ohe = OneHotEncoder(drop='if_binary', handle_unknown='infrequent_if_exist', min_frequency=1)
minmax = MinMaxScaler()
bucket_cond = KBinsDiscretizer(n_bins=10, encode='onehot', strategy='uniform')

numeric_columns = ['year', 'odometer']
categorical_columns = ['make', 'model', 'trim', 'model_trim', 'body',
                       'transmission', 'state', 'color', 'interior',
                       'color_interior']

col_transformer = ColumnTransformer(
  [('ohe', ohe, categorical_columns),
   ('minmax', minmax, numeric_columns),
   ('bucket_cond', bucket_cond, ['condition'])])

pipeline = Pipeline(steps=[('drop_cols' , drop_cols),
                           ('col_transformer', col_transformer),
                           ('model', model)])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('drop_cols',
                 FunctionTransformer(func=<function preproc_cols at 0x7c2c654d5b20>,
                                     kw_args={'drop_cols': ['Unnamed: 0',
                                                            'mmr']})),
                ('col_transformer',
                 ColumnTransformer(transformers=[('ohe',
                                                  OneHotEncoder(drop='if_binary',
                                                                handle_unknown='infrequent_if_exist',
                                                                min_frequency=1),
                                                  ['make', 'model', 'trim',
                                                   'model_trim', 'body',
                                                   'transmission', 'state',
                                                   'color', 'interior',
                                                   'color_interior']),
                                                 ('minmax', MinMaxScaler(),
                                                  ['year', 'odometer']),
                                                 ('bucket_cond',
                                                  KBinsDiscretizer(n_bins=10,
                                                                   strategy='uniform'),
                                                  ['condition'])])),
                ('model', LinearRegression())])

In [37]:
print('R2:', pipeline.score(X_valid, y_valid))
print('RMSE:',math.sqrt(mean_squared_error(y_valid, pipeline.predict(X_valid))))
print('MAE:', mean_absolute_error(y_valid, pipeline.predict(X_valid)))

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2, 3, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

R2: 0.8972128956965144

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2, 3, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

RMSE: 3122.142483462928
MAE: 1864.2914321435073

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2, 3, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

# **Ajuste de Hiperparamatros**
- Busqueda por grilla
- Busqueda Aleatoria
- Busquedq Bayesiana

In [38]:
import pandas as pd

from sklearn.preprocessing import (OneHotEncoder, MinMaxScaler,
                                   FunctionTransformer,
                                   KBinsDiscretizer)
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

y_train = train_df['sellingprice']
X_train = train_df.drop('sellingprice', axis=1)

def preproc_cols(df, drop_cols):

    df['model_trim'] = df['model'] + df['trim']
    df['model_trim'] = df['model_trim'].str.lower()

    df['color_interior'] = df['color'] + df['interior']
    df['color_interior'] = df['color_interior'].str.lower()

    return df.drop(drop_cols, axis=1)

drop_cols = FunctionTransformer(preproc_cols, kw_args={"drop_cols":['Unnamed: 0', 'mmr']})
ohe = OneHotEncoder(drop='if_binary', handle_unknown='infrequent_if_exist', min_frequency=1)
minmax = MinMaxScaler()
bucket_cond = KBinsDiscretizer(n_bins=10, encode='onehot',
    strategy='uniform')
bucket_odo = KBinsDiscretizer(n_bins=10, encode='onehot',
    strategy='quantile')
bucket_year = KBinsDiscretizer(n_bins=10, encode='onehot',
    strategy='uniform')

categorical_columns = ['make', 'model', 'trim', 'model_trim', 'body',
                       'transmission', 'state', 'color', 'interior',
                       'color_interior']

col_transformer = ColumnTransformer(
  [('ohe', ohe, categorical_columns),
   ('minmax', minmax, numeric_columns),
   ('bucket_cond', bucket_cond, ['condition']),
   ('bucket_odo', bucket_odo, ['odometer']),
   ('bucket_year', bucket_year, ['year'])]
   )

pipeline = Pipeline(steps=[('drop_cols' , drop_cols),
                           ('col_transformer', col_transformer),
                           ('model', model)])

grid_params = {'col_transformer__bucket_cond__n_bins': range(8,13),
               'col_transformer__bucket_odo__n_bins': range(8,13),
               'col_transformer__bucket_year__n_bins': range(8,13),
               'col_transformer__ohe__min_frequency': range(5)
              }

from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV

grid_search = HalvingGridSearchCV(pipeline, grid_params,
                                  cv=3, verbose=0,
                                  scoring='neg_mean_absolute_error')

grid_search.fit(X_train, y_train)
print(grid_search.best_params_)

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 6, 8, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [0, 1, 2, 3, 4, 8, 9] during transform. These unknown categories will be encoded as all zeros

{'col_transformer__bucket_cond__n_bins': 12, 'col_transformer__bucket_odo__n_bins': 12, 'col_transformer__bucket_year__n_bins': 12, 'col_transformer__ohe__min_frequency': 1}

In [41]:
print(grid_search.best_params_)

{'col_transformer__bucket_cond__n_bins': 12, 'col_transformer__bucket_odo__n_bins': 12, 'col_transformer__bucket_year__n_bins': 12, 'col_transformer__ohe__min_frequency': 1}

In [42]:
y_valid = valid_df['sellingprice']
X_valid = valid_df.drop('sellingprice', axis=1)

print('MAE:', mean_absolute_error(y_valid, grid_search.predict(X_valid)))
print('RMSE:', math.sqrt(mean_squared_error(y_valid, grid_search.predict(X_valid))))

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2, 3, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

MAE: 1752.5497581549514
RMSE: 2915.991155289307

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [1, 2, 3, 9] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [ ]:

y_valid = valid_df['sellingprice']
X_valid = valid_df.drop('sellingprice', axis=1)

print('MAE:', mean_absolute_error(y_valid, grid_search.predict(X_valid)))